version: '3.8'
services:
  postgres_db:
    image: 'postgres'
    # restart: always
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: simanto
    # ports:
    #   - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
  
volumes:
  db-data:
  
    
