version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
  postgres_db:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simanto
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  
    
